name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-v${{ secrets.BUILD_CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}

      - name: Pre-Install
        run: rm -rf node_modules

      - name: Installing the app
        run: yarn install --frozen-lockfile

      - name: Building the app
        run: yarn build

      - name: Exporting static version of the app
        run: yarn export

      - name: Configuring Github Pages
        run: |
          touch ./out/.nojekyll
          touch ./out/CNAME
          echo 'headunit.js.org' > ./out/CNAME

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          token: ${{ secrets.DEPLOY_TOKEN }} # This option defaults to the repository scoped GitHub Token.
          repository-name: riipandi/headunit # Specify the github repository path.
          branch: gh-pages # The branch the action should deploy to.
          folder: out # The folder the action should deploy.
